# **NUMPY**

**Create 1D and 2D arrays.**

In [2]:
import numpy as np

arr_1d = np.array([1,23,4,56,54,89,20])

arr_2d = np.array([
    [1,23,4,56,54,89,20] ,
    [1,23,4,56,54,89,20]]
)



**Perform arithmetic operations on arrays.**

In [3]:
calculations_arr = arr_1d + arr_2d
print(calculations_arr, "\n--------------------------------\n")
calculations_arr = arr_1d - arr_2d
print(calculations_arr, "\n--------------------------------\n")
calculations_arr = arr_1d * arr_2d
print(calculations_arr, "\n--------------------------------\n")
calculations_arr = arr_1d / arr_2d
print(calculations_arr, "\n--------------------------------\n")
calculations_arr = arr_2d[0] + arr_2d[1]
print(calculations_arr, "\n--------------------------------\n")
calculations_arr = arr_2d[0] / arr_2d[1]
print(calculations_arr, "\n--------------------------------\n")

[[  2  46   8 112 108 178  40]
 [  2  46   8 112 108 178  40]] 
--------------------------------

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]] 
--------------------------------

[[   1  529   16 3136 2916 7921  400]
 [   1  529   16 3136 2916 7921  400]] 
--------------------------------

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]] 
--------------------------------

[  2  46   8 112 108 178  40] 
--------------------------------

[1. 1. 1. 1. 1. 1. 1.] 
--------------------------------



**Find the maximum, minimum, mean, and sum of an array.**

In [4]:
print("MAXIMUM VALUE : " , arr_1d.max())
print("MINIMUM VALUE : " , arr_1d.min())
print("MEAN : " , arr_1d.mean())
print("SUM OF 1D-ARRAY : " , arr_1d.sum())
print("\n--------------------------\n")
print("MEAN : " , arr_2d.mean())
print("SUM OF 2D-ARRAY : " , arr_2d.sum())

MAXIMUM VALUE :  89
MINIMUM VALUE :  1
MEAN :  35.285714285714285
SUM OF 1D-ARRAY :  247

--------------------------

MEAN :  35.285714285714285
SUM OF 2D-ARRAY :  494


**Reshape arrays into different dimensions.**


In [19]:
print(arr_2d.reshape(7,2))
print("\n--------------------------\n")
print(arr_1d.reshape(7,1))

arr_3d = np.array([
    [1,23,4,56,54,89,20],
     [1,23,4,56,54,89,20],
    [1,23,4,56,54,89,20],
     [1,23,4,56,54,89,20]
])

print("\nOriginal : \n" , arr_3d)
print(arr_3d.shape)

print("\nReshaped :\n " , arr_3d.reshape(7,4))
print("\nReshaped :\n " , arr_3d.reshape(14,2))



[[ 1 23]
 [ 4 56]
 [54 89]
 [20  1]
 [23  4]
 [56 54]
 [89 20]]

--------------------------

[[ 1]
 [23]
 [ 4]
 [56]
 [54]
 [89]
 [20]]

Original : 
 [[ 1 23  4 56 54 89 20]
 [ 1 23  4 56 54 89 20]
 [ 1 23  4 56 54 89 20]
 [ 1 23  4 56 54 89 20]]
(4, 7)

Reshaped :
  [[ 1 23  4 56]
 [54 89 20  1]
 [23  4 56 54]
 [89 20  1 23]
 [ 4 56 54 89]
 [20  1 23  4]
 [56 54 89 20]]

Reshaped :
  [[ 1 23]
 [ 4 56]
 [54 89]
 [20  1]
 [23  4]
 [56 54]
 [89 20]
 [ 1 23]
 [ 4 56]
 [54 89]
 [20  1]
 [23  4]
 [56 54]
 [89 20]]


**Slice and index arrays.**

In [31]:
arr = arr_3d[0:2 , 1:3]

print("Original Array : \n " , arr_3d, " \n-------------------------\n")
print("Values from first 2 rows of Columns 2&3 :\n " , arr)
print(" \n-------------------------\n")
print("Values of first row :\n" , arr_3d[0])
print(" \n-------------------------\n")
print("first 5 values of first row :\n" , arr_3d[0,0:5])
print(" \n-------------------------\n")
print("Last 5 values of all rows :\n" , arr_3d[:,-1:-6:-1])
#without "-1 in above line it is giving empty list , and by using it , it reverse the order"

Original Array : 
  [[ 1 23  4 56 54 89 20]
 [ 1 23  4 56 54 89 20]
 [ 1 23  4 56 54 89 20]
 [ 1 23  4 56 54 89 20]]  
-------------------------

Values from first 2 rows of Columns 2&3 :
  [[23  4]
 [23  4]]
 
-------------------------

Values of first row :
 [ 1 23  4 56 54 89 20]
 
-------------------------

first 5 values of first row :
 [ 1 23  4 56 54]
 
-------------------------

Last 5 values of all rows :
 []
 
-------------------------

